version: "3.2"

services:
  traefik:
    image: "traefik:v3.0"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt/acme.json:/letsencrypt/acme.json"
    command:
      # docker swarm
      - --providers.docker=true
      - --providers.swarm.endpoint=tcp://127.0.0.1:2377
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=public

      # portas e redirecionamento
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecured
      - --entrypoints.web.http.redirections.entryPoint.scheme=https

      # ativacao de api e dashboard
      - --api
      - --api.debug=true
      - --api.dashboard=true
      #- --api.insecure=true Desativado para testar se funciona corretamente com seguranca

      # letsencrypt, geracao de certificados
      - --certificatesresolvers.leresolver.acme.email=p4n1c0021@gmail.com
      - --certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web

      # logs do traefik
      - --log.level=ERROR
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`13.58.42.254`)
        - traefik.http.routers.traefik.tls=true
        - traefik.http.routers.traefik.tls.certresolver=leresolver
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.api.loadbalancer.server.port=8080

networks:
  public:
    external: true
