{
 "title": "Docker Swarm",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(container_label_com_docker_swarm_node_id)"
    }
   },
   {
    "name": "Stack",
    "query": {
     "query": "label_values(container_label_com_docker_stack_namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(container_label_com_docker_swarm_service_name)"
    }
   },
   {
    "name": "Container",
    "query": {
     "query": "label_values(container_label_com_docker_swarm_task_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(container_label_com_docker_stack_namespace) (container_tasks_state{container_label_com_docker_stack_namespace=~\".+\", container_label_com_docker_swarm_node_id=~\".+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(container_label_com_docker_swarm_service_name) (container_tasks_state{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Containers - Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count by(container_label_com_docker_swarm_service_name) (rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage - Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(container_label_com_docker_swarm_service_name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"}[1m]))* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage - Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container_label_com_docker_swarm_service_name) (container_memory_working_set_bytes{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Cache - Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container_label_com_docker_swarm_service_name) (container_memory_cache{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network received - Service",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(container_label_com_docker_swarm_service_name) (rate(container_network_receive_bytes_total{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network transmitted - Service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(container_label_com_docker_swarm_service_name) (rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers - Stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "count by(container_label_com_docker_stack_namespace) (rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage - Stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(container_label_com_docker_stack_namespace) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"}[1m])) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage - Stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(container_label_com_docker_stack_namespace) (container_memory_working_set_bytes{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Cache - Stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(container_label_com_docker_stack_namespace) (container_memory_cache{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network received - Stack",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(container_label_com_docker_stack_namespace) (rate(container_network_receive_bytes_total{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network transmitted - Stack",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(container_label_com_docker_stack_namespace) (rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_node_id=~\"$Node\", container_label_com_docker_stack_namespace=~\"$Stack\", container_label_com_docker_swarm_service_name=~\"$Service\", container_label_com_docker_swarm_task_name=~\"$Container\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}